build:
  command: "pdflatex"
  compile: True
  flags: [ "-shell-escape" ]
  remove_files: True
  shell-escape: True

main:
  author: ""
  date: ""
  document_class: "article"
  packages: ["amsmath"]
  other_preamble: ""
  text: "gdfgdfgdfgdfg"
  title: ""

save:
  name: "test.tex"
  overwrite: True
  path: "."
  print: False
  return: True
  save:  True
