# Configuration blueprint, that is the variables that can be set in the configuration file,
# and their types. The types are used to check the validity of the configuration file.

build:
  bibtex: bool
  command: str
  compile: bool
  flags: list
  remove_files: bool
  shell-escape: bool

main:
  author: str
  date: str
  document_class: [str, list]
  other_preamble: str
  packages: list
  text: str
  title: str

save:
  name: str
  overwrite: bool
  path: str
  print: bool
  return: bool
  save:  bool
